<?php

/**
 * ## Test of all models defined
 *
 * ------
 *
 * This file is auto-generated by: Workbench\App\Console\Commands\RunTestProjectCommand
 * rewrite this test-file on the console with: php artisan run:test-project
 */

namespace SchenkeIo\LaravelRelationManager\Tests\Application;

use Illuminate\Foundation\Testing\RefreshDatabase;
use SchenkeIo\LaravelRelationManager\Phpunit\AssertModelRelations;
use SchenkeIo\LaravelRelationManager\Tests\TestCase;
use Workbench\App\Console\Commands\RunTestProjectCommand;

class TestProjectTest extends TestCase
{
    use AssertModelRelations;
    use RefreshDatabase;

    /**
     * @group GenerateProjectTestFile
     *
     * Since this class is written by the Command file Workbench\App\Console\Commands\RunTestProjectCommand
     * it is risky when changes in the Command file are not transferred here
     * To update this file just run: php artisan run:test-project
     */
    public function testCommandFileIsOlderThanThisTestFile(): void
    {
        $this->assertFirstClassIsOlderThanSecondClass(
            RunTestProjectCommand::class,
            __CLASS__
        );
    }

    /**
     * Model Workbench\App\Models\Capital
     *
     * @group GenerateProjectTestFile
     */
    public function testModelCapitalHas_1StrictRelationshipAndWorks(): void
    {
        $this->assertModelWorks("Workbench\App\Models\Capital");
        $this->assertModelBelongsTo('Workbench\App\Models\Capital', 'Workbench\App\Models\Country');
        $this->assertModelRelationCount('Workbench\App\Models\Capital', 1);
    }

    /**
     * Model Workbench\App\Models\City
     *
     * @group GenerateProjectTestFile
     */
    public function testModelCityHas_3StrictRelationshipsAndWorks(): void
    {
        $this->assertModelWorks("Workbench\App\Models\City");
        $this->assertModelIsManyToMany('Workbench\App\Models\City', 'Workbench\App\Models\Highway');
        $this->assertModelHasOneThrough('Workbench\App\Models\City', 'Workbench\App\Models\Country');
        $this->assertModelBelongsTo('Workbench\App\Models\City', 'Workbench\App\Models\Region');
        $this->assertModelRelationCount('Workbench\App\Models\City', 3);
    }

    /**
     * Model Workbench\App\Models\Country
     *
     * @group GenerateProjectTestFile
     */
    public function testModelCountryHas_3StrictRelationshipsAndWorks(): void
    {
        $this->assertModelWorks("Workbench\App\Models\Country");
        $this->assertModelHasOne('Workbench\App\Models\Country', 'Workbench\App\Models\Capital');
        $this->assertModelHasMany('Workbench\App\Models\Country', 'Workbench\App\Models\Region');
        $this->assertModelHasManyThrough('Workbench\App\Models\Country', 'Workbench\App\Models\City');
        $this->assertModelRelationCount('Workbench\App\Models\Country', 3);
    }

    /**
     * Model Workbench\App\Models\Highway
     *
     * @group GenerateProjectTestFile
     */
    public function testModelHighwayHas_1StrictRelationshipAndWorks(): void
    {
        $this->assertModelWorks("Workbench\App\Models\Highway");
        $this->assertModelBelongsToMany('Workbench\App\Models\Highway', 'Workbench\App\Models\City');
        $this->assertModelRelationCount('Workbench\App\Models\Highway', 1);
    }

    /**
     * Model Workbench\App\Models\Region
     *
     * @group GenerateProjectTestFile
     */
    public function testModelRegionHas_3StrictRelationshipsAndWorks(): void
    {
        $this->assertModelWorks("Workbench\App\Models\Region");
        $this->assertModelBelongsTo('Workbench\App\Models\Region', 'Workbench\App\Models\Country');
        $this->assertModelHasMany('Workbench\App\Models\Region', 'Workbench\App\Models\City');
        $this->assertModelHasOneThrough('Workbench\App\Models\Region', 'Workbench\App\Models\Capital');
        $this->assertModelRelationCount('Workbench\App\Models\Region', 3);
    }

    /**
     * Model Workbench\App\Models\Single
     *
     * @group GenerateProjectTestFile
     */
    public function testModelSingleHas_0StrictRelationshipsAndWorks(): void
    {
        $this->assertModelWorks("Workbench\App\Models\Single");
        $this->assertModelRelationCount('Workbench\App\Models\Single', 0);
    }
}
