<?php

/**
 * ## Test of all models defined
 *
 * ------
 *
 * This file is auto-generated by: Workbench\App\Console\Commands\RunTestProjectManagerCommand
 * rewrite this test-file on the console with: php artisan run:test-project
 */

namespace SchenkeIo\LaravelRelationManager\Tests\Application;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Schema;
use PHPUnit\Framework\Attributes\Group;
use PHPUnit\Framework\Attributes\TestDox;
use SchenkeIo\LaravelRelationManager\Tests\TestCase;
use SchenkeIo\LaravelRelationManager\Traits\AssertModelRelations;
use Workbench\App\Console\Commands\RunTestProjectManagerCommand;

class TestProjectTest extends TestCase
{
    use RefreshDatabase;
    use AssertModelRelations;

    /**
     * @return void
     *
     * Since this class is written by the Command file Workbench\App\Console\Commands\RunTestProjectManagerCommand
     * it is risky when changes in the Command file are not transferred here
     * To update this file just run: php artisan run:test-project
     */
    #[Group('GenerateProjectTestFile')]
    public function testCommandFileIsOlderThanThisTestFile(): void
    {
        $this->assertFirstClassIsOlderThanSecondClass(
            RunTestProjectManagerCommand::class,
            __CLASS__
        );
    }

    /**
     * Model Workbench\App\Models\Capital
     */
    #[Group('GenerateProjectTestFile')]
    public function testModelCapitalHas_2StrictRelationshipsAndWorks(): void
    {
        $this->assertModelMorphOne('Workbench\App\Models\Capital', 'Workbench\App\Models\Location');
        $this->assertModelBelongsTo('Workbench\App\Models\Capital', 'Workbench\App\Models\Country');
        $this->assertModelRelationCount('Workbench\App\Models\Capital', 2);
    }

    /**
     * Model Workbench\App\Models\City
     */
    #[Group('GenerateProjectTestFile')]
    public function testModelCityHas_5StrictRelationshipsAndWorks(): void
    {
        $this->assertModelBelongsToMany('Workbench\App\Models\City', 'Workbench\App\Models\Highway');
        $this->assertModelHasOneThrough('Workbench\App\Models\City', 'Workbench\App\Models\Country');
        $this->assertModelMorphToMany('Workbench\App\Models\City', 'Workbench\App\Models\Tag');
        $this->assertModelMorphOne('Workbench\App\Models\City', 'Workbench\App\Models\Location');
        $this->assertModelBelongsTo('Workbench\App\Models\City', 'Workbench\App\Models\Region');
        $this->assertModelRelationCount('Workbench\App\Models\City', 5);
    }

    /**
     * Model Workbench\App\Models\Country
     */
    #[Group('GenerateProjectTestFile')]
    public function testModelCountryHas_4StrictRelationshipsAndWorks(): void
    {
        $this->assertModelHasOne('Workbench\App\Models\Country', 'Workbench\App\Models\Capital');
        $this->assertModelHasOneIndirect('Workbench\App\Models\Country', 'Workbench\App\Models\City');
        $this->assertModelHasManyThrough('Workbench\App\Models\Country', 'Workbench\App\Models\City');
        $this->assertModelHasMany('Workbench\App\Models\Country', 'Workbench\App\Models\Region');
        $this->assertModelRelationCount('Workbench\App\Models\Country', 4);
    }

    /**
     * Model Workbench\App\Models\Highway
     */
    #[Group('GenerateProjectTestFile')]
    public function testModelHighwayHas_2StrictRelationshipsAndWorks(): void
    {
        $this->assertModelBelongsToMany('Workbench\App\Models\Highway', 'Workbench\App\Models\City');
        $this->assertModelMorphMany('Workbench\App\Models\Highway', 'Workbench\App\Models\Location');
        $this->assertModelRelationCount('Workbench\App\Models\Highway', 2);
    }

    /**
     * Model Workbench\App\Models\Location
     */
    #[Group('GenerateProjectTestFile')]
    public function testModelLocationHas_1StrictRelationshipAndWorks(): void
    {
        $this->assertModelMorphTo('Workbench\App\Models\Location');
        $this->assertModelRelationCount('Workbench\App\Models\Location', 1);
    }

    /**
     * Model Workbench\App\Models\Region
     */
    #[Group('GenerateProjectTestFile')]
    public function testModelRegionHas_4StrictRelationshipsAndWorks(): void
    {
        $this->assertModelBelongsTo('Workbench\App\Models\Region', 'Workbench\App\Models\Country');
        $this->assertModelMorphToMany('Workbench\App\Models\Region', 'Workbench\App\Models\Tag');
        $this->assertModelHasMany('Workbench\App\Models\Region', 'Workbench\App\Models\City');
        $this->assertModelHasOneThrough('Workbench\App\Models\Region', 'Workbench\App\Models\Capital');
        $this->assertModelRelationCount('Workbench\App\Models\Region', 4);
    }

    /**
     * Model Workbench\App\Models\Single
     */
    #[Group('GenerateProjectTestFile')]
    public function testModelSingleHas_0StrictRelationshipsAndWorks(): void
    {
        $this->assertModelRelationCount('Workbench\App\Models\Single', 0);
    }

    /**
     * Model Workbench\App\Models\Tag
     */
    #[Group('GenerateProjectTestFile')]
    public function testModelTagHas_2StrictRelationshipsAndWorks(): void
    {
        $this->assertModelMorphedByMany('Workbench\App\Models\Tag', 'Workbench\App\Models\City');
        $this->assertModelMorphedByMany('Workbench\App\Models\Tag', 'Workbench\App\Models\Region');
        $this->assertModelRelationCount('Workbench\App\Models\Tag', 2);
    }

    #[Group('GenerateProjectTestFile')]
    public function testDatabaseTable_capitals()
    {
        $this->assertTrue(Schema::hasTable('capitals'));
        $this->assertTrue(Schema::hasColumn('capitals','country_id'));
    }

    #[Group('GenerateProjectTestFile')]
    public function testDatabaseTable_cities()
    {
        $this->assertTrue(Schema::hasTable('cities'));
        $this->assertTrue(Schema::hasColumn('cities','region_id'));
    }

    #[Group('GenerateProjectTestFile')]
    public function testDatabaseTable_city_highway()
    {
        $this->assertTrue(Schema::hasTable('city_highway'));
        $this->assertTrue(Schema::hasColumn('city_highway','city_id'));
        $this->assertTrue(Schema::hasColumn('city_highway','highway_id'));
    }

    #[Group('GenerateProjectTestFile')]
    public function testDatabaseTable_countries()
    {
        $this->assertTrue(Schema::hasTable('countries'));
    }

    #[Group('GenerateProjectTestFile')]
    public function testDatabaseTable_highways()
    {
        $this->assertTrue(Schema::hasTable('highways'));
    }

    #[Group('GenerateProjectTestFile')]
    public function testDatabaseTable_locations()
    {
        $this->assertTrue(Schema::hasTable('locations'));
        $this->assertTrue(Schema::hasColumn('locations','locationable_id'));
        $this->assertTrue(Schema::hasColumn('locations','locationable_type'));
    }

    #[Group('GenerateProjectTestFile')]
    public function testDatabaseTable_regions()
    {
        $this->assertTrue(Schema::hasTable('regions'));
        $this->assertTrue(Schema::hasColumn('regions','country_id'));
    }

    #[Group('GenerateProjectTestFile')]
    public function testDatabaseTable_singles()
    {
        $this->assertTrue(Schema::hasTable('singles'));
    }

    #[Group('GenerateProjectTestFile')]
    public function testDatabaseTable_tags()
    {
        $this->assertTrue(Schema::hasTable('tags'));
    }
}
