<?php

/**
 * ## possible assertions of Eloquent Models
 * add this file into your Phpunit test files
 *
 * ------
 *
 * This file is auto-generated by:
 * SchenkeIo\LaravelRelationManager\Writer\GenerateAssertModelRelationsTrait
 * using the data from: @see SchenkeIo\LaravelRelationManager\Define\RelationsEnum
 */

namespace SchenkeIo\LaravelRelationManager\Phpunit;

use SchenkeIo\LaravelRelationManager\Data\ModelCountData;
use SchenkeIo\LaravelRelationManager\Data\ModelRelationData;
use SchenkeIo\LaravelRelationManager\Define\RelationsEnum;

trait AssertModelRelations
{
    public function assertModelBackedEnumWorks(string $model): void
    {
        \PHPUnit\Framework\assertThat($model, new ModelBackedEnumConstraint());
    }

    public function assertFirstClassIsOlderThanSecondClass(string $class1, string $class2): void
    {
        \PHPUnit\Framework\assertThat(
            new ModelRelationData($class1, $class2, RelationsEnum::noRelation),
            new ClassAgeConstraint()
        );
    }

    public function assertModelRelationCount(string $model, int $count): void
    {
        \PHPUnit\Framework\assertThat(
            new ModelCountData($model, $count),
            new RelationshipCountConstraint()
        );
    }

    public function assertModelHasOne(string $modelFrom, string $modelTo): void
    {
        \PHPUnit\Framework\assertThat(
            new ModelRelationData($modelFrom, $modelTo, RelationsEnum::hasOne),
            new RelationshipExistsConstraint()
        );
    }

    public function assertModelHasMany(string $modelFrom, string $modelTo): void
    {
        \PHPUnit\Framework\assertThat(
            new ModelRelationData($modelFrom, $modelTo, RelationsEnum::hasMany),
            new RelationshipExistsConstraint()
        );
    }

    public function assertModelHasOneThrough(string $modelFrom, string $modelTo): void
    {
        \PHPUnit\Framework\assertThat(
            new ModelRelationData($modelFrom, $modelTo, RelationsEnum::hasOneThrough),
            new RelationshipExistsConstraint()
        );
    }

    public function assertModelHasManyThrough(string $modelFrom, string $modelTo): void
    {
        \PHPUnit\Framework\assertThat(
            new ModelRelationData($modelFrom, $modelTo, RelationsEnum::hasManyThrough),
            new RelationshipExistsConstraint()
        );
    }

    public function assertModelBelongsToMany(string $modelFrom, string $modelTo): void
    {
        \PHPUnit\Framework\assertThat(
            new ModelRelationData($modelFrom, $modelTo, RelationsEnum::belongsToMany),
            new RelationshipExistsConstraint()
        );
    }

    public function assertModelBelongsTo(string $modelFrom, string $modelTo): void
    {
        \PHPUnit\Framework\assertThat(
            new ModelRelationData($modelFrom, $modelTo, RelationsEnum::belongsTo),
            new RelationshipExistsConstraint()
        );
    }

    public function assertModelIsSingle(string $model): void
    {
        \PHPUnit\Framework\assertThat($model, new NoRelationshipConstraint());
    }

    public function assertModelMorphTo(string $modelFrom): void
    {
        \PHPUnit\Framework\assertThat(
            new ModelRelationData($modelFrom, $modelFrom, RelationsEnum::morphTo),
            new RelationshipExistsConstraint()
        );
    }

    public function assertModelMorphOne(string $modelFrom, string $modelTo): void
    {
        \PHPUnit\Framework\assertThat(
            new ModelRelationData($modelFrom, $modelTo, RelationsEnum::morphOne),
            new RelationshipExistsConstraint()
        );
    }

    public function assertModelMorphMany(string $modelFrom, string $modelTo): void
    {
        \PHPUnit\Framework\assertThat(
            new ModelRelationData($modelFrom, $modelTo, RelationsEnum::morphMany),
            new RelationshipExistsConstraint()
        );
    }

    public function assertModelCastEnum(string $modelFrom, string $modelTo): void
    {
        \PHPUnit\Framework\assertThat(
            new ModelRelationData($modelFrom, $modelTo, RelationsEnum::castEnum),
            new RelationshipExistsConstraint()
        );
    }

    public function assertModelIsManyToMany(string $modelFrom, string $modelTo): void
    {
        \PHPUnit\Framework\assertThat(
            new ModelRelationData($modelFrom, $modelTo, RelationsEnum::isManyToMany),
            new RelationshipExistsConstraint()
        );
    }
}
