<?php

/**
 * ## possible assertions of Eloquent Models
 * add this file into your Phpunit test files
 *
 * ------
 *
 * This file is auto-generated by:
 * SchenkeIo\LaravelRelationManager\Writer\GenerateAssertModelRelationshipsTrait
 * using the data from: @see SchenkeIo\LaravelRelationManager\Define\RelationshipEnum
 */

namespace SchenkeIo\LaravelRelationManager\Phpunit;

use SchenkeIo\LaravelRelationManager\Data\ModelCountData;
use SchenkeIo\LaravelRelationManager\Data\RelationData;
use SchenkeIo\LaravelRelationManager\Define\RelationshipEnum;

trait AssertModelRelationships
{
    public function assertModelWorks(string $model): void
    {
        \PHPUnit\Framework\assertThat($model, new ModelConstraint());
    }

    public function assertFirstClassIsOlderThanSecondClass(string $class1, string $class2): void
    {
        \PHPUnit\Framework\assertThat(
            new RelationData($class1, $class2, RelationshipEnum::noRelation),
            new ClassAgeConstraint()
        );
    }

    public function assertModelRelationCount(string $model, int $count): void
    {
        \PHPUnit\Framework\assertThat(
            new ModelCountData($model, $count),
            new RelationshipCountConstraint()
        );
    }

    public function assertModelHasOne(string $modelFrom, string $modelTo): void
    {
        \PHPUnit\Framework\assertThat(
            new RelationData($modelFrom, $modelTo, RelationshipEnum::hasOne),
            new RelationshipExistsConstraint()
        );
    }

    public function assertModelHasMany(string $modelFrom, string $modelTo): void
    {
        \PHPUnit\Framework\assertThat(
            new RelationData($modelFrom, $modelTo, RelationshipEnum::hasMany),
            new RelationshipExistsConstraint()
        );
    }

    public function assertModelHasOneThrough(string $modelFrom, string $modelTo): void
    {
        \PHPUnit\Framework\assertThat(
            new RelationData($modelFrom, $modelTo, RelationshipEnum::hasOneThrough),
            new RelationshipExistsConstraint()
        );
    }

    public function assertModelHasManyThrough(string $modelFrom, string $modelTo): void
    {
        \PHPUnit\Framework\assertThat(
            new RelationData($modelFrom, $modelTo, RelationshipEnum::hasManyThrough),
            new RelationshipExistsConstraint()
        );
    }

    public function assertModelBelongsToMany(string $modelFrom, string $modelTo): void
    {
        \PHPUnit\Framework\assertThat(
            new RelationData($modelFrom, $modelTo, RelationshipEnum::belongsToMany),
            new RelationshipExistsConstraint()
        );
    }

    public function assertModelBelongsTo(string $modelFrom, string $modelTo): void
    {
        \PHPUnit\Framework\assertThat(
            new RelationData($modelFrom, $modelTo, RelationshipEnum::belongsTo),
            new RelationshipExistsConstraint()
        );
    }

    public function assertModelIsSingle(string $model): void
    {
        \PHPUnit\Framework\assertThat($model, new NoRelationshipConstraint());
    }

    public function assertModelIsOneToOne(string $modelFrom, string $modelTo): void
    {
        \PHPUnit\Framework\assertThat(
            new RelationData($modelFrom, $modelTo, RelationshipEnum::isOneToOne),
            new RelationshipExistsConstraint()
        );
    }

    public function assertModelIsOneToMany(string $modelFrom, string $modelTo): void
    {
        \PHPUnit\Framework\assertThat(
            new RelationData($modelFrom, $modelTo, RelationshipEnum::isOneToMany),
            new RelationshipExistsConstraint()
        );
    }

    public function assertModelIsManyToMany(string $modelFrom, string $modelTo): void
    {
        \PHPUnit\Framework\assertThat(
            new RelationData($modelFrom, $modelTo, RelationshipEnum::isManyToMany),
            new RelationshipExistsConstraint()
        );
    }
}
