<?php

/**
 * ## Description of all the possible relationships
 *
 * ------
 *
 * This file is auto-generated by:
 * SchenkeIo\LaravelRelationManager\Writer\GenerateRelationTypesTrait
 * using the data from: SchenkeIo\LaravelRelationManager\Enums\Relation
 */

namespace SchenkeIo\LaravelRelationManager\Traits;

use SchenkeIo\LaravelRelationManager\Define\DefineRelation;
use SchenkeIo\LaravelRelationManager\Enums\Relation;

trait RelationTypes
{
    public function hasOne(string $modelName, bool $addReverseRelation): DefineRelation
    {
        return $this->buildRelation(
            $modelName,
            $addReverseRelation,
            Relation::hasOne,
            Relation::belongsTo
        );
    }

    public function hasMany(string $modelName, bool $addReverseRelation): DefineRelation
    {
        return $this->buildRelation(
            $modelName,
            $addReverseRelation,
            Relation::hasMany,
            Relation::belongsTo
        );
    }

    public function hasOneThrough(string $modelName): DefineRelation
    {
        return $this->buildRelation(
            $modelName,
            false,
            Relation::hasOneThrough,
            Relation::noRelation
        );
    }

    public function hasManyThrough(string $modelName): DefineRelation
    {
        return $this->buildRelation(
            $modelName,
            false,
            Relation::hasManyThrough,
            Relation::noRelation
        );
    }

    public function belongsToMany(string $modelName, bool $addReverseRelation): DefineRelation
    {
        return $this->buildRelation(
            $modelName,
            $addReverseRelation,
            Relation::belongsToMany,
            Relation::belongsToMany
        );
    }

    public function morphOne(string $modelName, bool $addReverseRelation): DefineRelation
    {
        return $this->buildRelation(
            $modelName,
            $addReverseRelation,
            Relation::morphOne,
            Relation::morphTo
        );
    }

    public function morphMany(string $modelName, bool $addReverseRelation): DefineRelation
    {
        return $this->buildRelation(
            $modelName,
            $addReverseRelation,
            Relation::morphMany,
            Relation::morphTo
        );
    }

    public function morphToMany(string $modelName, bool $addReverseRelation): DefineRelation
    {
        return $this->buildRelation(
            $modelName,
            $addReverseRelation,
            Relation::morphToMany,
            Relation::morphedByMany
        );
    }

    public function morphedByMany(string $modelName): DefineRelation
    {
        return $this->buildRelation(
            $modelName,
            false,
            Relation::morphedByMany,
            Relation::noRelation
        );
    }

    public function hasOneIndirect(string $modelName): DefineRelation
    {
        return $this->buildRelation(
            $modelName,
            false,
            Relation::hasOneIndirect,
            Relation::noRelation
        );
    }
}
