<?php

namespace SchenkeIo\LaravelRelationManager\Writer;

use Nette;
use SchenkeIo\LaravelRelationManager\Data\ClassData;
use SchenkeIo\LaravelRelationManager\Data\ModelCountData;
use SchenkeIo\LaravelRelationManager\Data\RelationData;
use SchenkeIo\LaravelRelationManager\Define\RelationshipEnum;

class GenerateAssertModelRelationshipsTrait
{
    public static function getContent(): string
    {
        $location = 'SchenkeIo\LaravelRelationManager';
        $traitName = 'AssertModelRelationships';
        $file = new Nette\PhpGenerator\PhpFile;

        $file->addComment('## possible assertions of Eloquent Models');
        $file->addComment('add this file into your Phpunit test files');
        $file->addComment("\n------\n");
        $file->addComment('This file is auto-generated by: ');
        $file->addComment(__CLASS__);
        $file->addComment('using the data from: @see '.RelationshipEnum::class);

        $nameSpace = $file->addNamespace($location.'\Phpunit');
        $nameSpace->addUse(ModelCountData::class);
        $nameSpace->addUse(RelationData::class);
        $nameSpace->addUse(RelationshipEnum::class);
        $classWritten = [];
        foreach (RelationshipEnum::cases() as $case) {
            if ($case->askForModel()) {
                $class = $case->getClass();
                if (! in_array($class, $classWritten)) {
                    $nameSpace->addUse($class);
                    $classWritten[] = $class;
                }
            }
        }

        $trait = $nameSpace->addTrait($traitName);

        /*
         * does the model exists and works ?
         */
        $method = $trait->addMethod('assertModelWorks');
        $method->addParameter('model')->setType('string');
        $method->setReturnType('void');
        $method->addBody('\PHPUnit\Framework\assertThat($model, new ModelConstraint());');
        /*
         * check if first class is older than second
         */
        $method = $trait->addMethod('assertFirstClassIsOlderThanSecondClass');
        $method->addParameter('class1')->setType('string');
        $method->addParameter('class2')->setType('string');
        $method->setReturnType('void');
        $method->addBody('\PHPUnit\Framework\assertThat(');
        $method->addBody('    new RelationData($class1, $class2, RelationshipEnum::noRelation),');
        $method->addBody('    new ClassAgeConstraint()');
        $method->addBody(');');
        /*
         * count the relations in a model
         */
        $method = $trait->addMethod('assertModelRelationCount');
        $method->addParameter('model')->setType('string');
        $method->addParameter('count')->setType('int');
        $method->setReturnType('void');
        $method->addBody('\PHPUnit\Framework\assertThat(');
        $method->addBody('    new ModelCountData($model, $count),');
        $method->addBody('    new RelationshipCountConstraint()');
        $method->addBody(');');

        foreach (RelationshipEnum::cases() as $case) {
            if ($case == RelationshipEnum::isSingle) {
                $methodName = 'assertModelIsSingle';
                $method = $trait->addMethod($methodName);
                $method->addParameter('model')->setType('string');
                $method->setReturnType('void');
                $method->addBody('\PHPUnit\Framework\assertThat($model, new NoRelationshipConstraint());');
            } elseif ($case->hasAssertFunction()) {
                $method = $trait->addMethod($case->getAssertName());
                $method->addParameter('modelFrom')->setType('string');
                $method->addParameter('modelTo')->setType('string');
                $method->setReturnType('void');

                $relationClass = ClassData::take($case->getClass())->getShortNameWithClass();
                $method->addBody('\PHPUnit\Framework\assertThat(');
                $method->addBody('    new RelationData($modelFrom, $modelTo, RelationshipEnum::'.$case->name.'),');
                $method->addBody('    new RelationshipExistsConstraint()');
                $method->addBody(');');
            }

        }
        $printer = new Nette\PhpGenerator\PsrPrinter;

        return $printer->printFile($file);
    }
}
